dist: trusty
language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - valgrind

before_install:
  - export COREIRCONFIG="g++-4.9";
  - cmake .
  - make -j

script:
  - valgrind ./all-tests

compiler:
  - gcc

os:
- linux